import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { notFound } from "next/navigation";
import { defaultLocale, locales } from "../../i18n";
import Navbar from "@/components/navbar/navbar";
// STYLES
import "./globals.css";
import "swiper/css/bundle";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UDCARD",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: { locale: string };
}

export default function RootLayout(props: Props) {
  const { params, children } = props;
  const messages = useMessages();
  if (!locales.includes(params.locale)) notFound();
  return (
    <html lang={params.locale || defaultLocale}>
      <NextIntlClientProvider messages={messages}>
        <body className={montserrat.className}>
          <main className="w-full h-full mt-16 bg-gray-200 text-gray-900">
            <Navbar />
            {children}
          </main>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
